# Generated by Django 4.2 on 2026-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('cash', 'Espèces')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Paiement total'), ('deposit', 'Acompte'), ('installment', 'Paiement échelonné')], default='full', max_length=20),
        ),
    ]
