# Generated by Django 6.0.3 on 2026-05-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_destination',
            field=models.CharField(blank=True, choices=[('plage', 'Plage'), ('montagne', 'Montagne'), ('ville', 'Ville'), ('desert', 'Désert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('luxe', 'Luxe'), ('eco', 'Économique'), ('famille', 'Famille'), ('aventure', 'Aventure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
