# Generated by Django 6.0.3 on 2026-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
