# Generated by Django 6.0.3 on 2026-05-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_voyage_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='places',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='points_interet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
