# Generated by Django 6.0.3 on 2026-05-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_voyage_options_voyage_places_voyage_points_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_list', to='voyages.voyage')),
            ],
        ),
    ]
