# Generated by Django 4.2 on 2026-05-05 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='category',
            field=models.CharField(choices=[('plage', 'Plage'), ('montagne', 'Montagne'), ('ville', 'Ville'), ('desert', 'Désert')], default='ville', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='places',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
