# Generated by Django 4.2 on 2026-05-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_remove_voyage_options_option_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyage',
            options={'ordering': ['start_date'], 'verbose_name': 'Voyage', 'verbose_name_plural': 'Voyages'},
        ),
    ]
