# Generated by Django 4.2 on 2026-05-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_personnes_alter_reservation_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
