# Generated by Django 4.2 on 2026-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_options_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
