# Generated by Django 4.2 on 2026-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0007_alter_option_options_option_created_at'),
        ('reservations', '0007_alter_reservation_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='voyages.option'),
        ),
    ]
