# Generated by Django 6.0.3 on 2026-05-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Voyage',
        ),
    ]
